package edu.greenriver.sdev.food.models;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

// Author: Nathan Waters
// Date: 2/2/2024
// version: 1

/**
 * Entity class representing a recipe.
 * Uses JPA annotations for mapping to the database.
 * Lombok annotations are used for generating getters, setters, constructors, and toString.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Recipe {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String name;
    private String url;
    private String author;

    @ElementCollection
    private List<String> ingredients;
    @ElementCollection
    private List<String> method;

    // Constructors, access methods, and toString are being generated by Lombok.

}
