package edu.greenriver.sdev.food.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// Author: Nathan Waters
// Date: 2/2/2024
// version: 1

/**
 * Entity class representing a review for a recipe.
 * Uses JPA annotations for mapping to the database.
 * Lombok annotations are used for generating getters, setters, constructors, and toString.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String recipeName;
    private int stars;
    private String review;

    // Constructors, access methods, and toString are being generated by Lombok.
}